apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-release
  namespace: app-release
spec:
  selector:
    matchLabels:
      app: app-release
      group: app-release
  replicas: 2
  template:
    metadata:
      labels:
        app: app-release
        group: app-release
    spec:
      containers:
        - name: app-release
          image:  {{ .Values.imageRepo }}/{{ .Values.imageName }}:{{ .Values.imageTag }}
          resources:
            requests:
              cpu: "{{ .Values.cpuRequests }}"
              memory: "{{ .Values.memoryRequests }}"
            limits:
              memory: "{{ .Values.memoryLimits }}"
              cpu: "{{ .Values.cpuLimits }}"
          ports:
            - containerPort: {{ .Values.jenkinsPort }}
            - containerPort: 80              
      {{- if eq .Values.environment "prod" }}
      nodeSelector:
        spotinst.io/node-lifecycle: od
      {{ end }}
