apiVersion: v1
kind: Service
metadata:
  name: app-release-lb
  namespace: app-release
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "120"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "True"
spec:
  selector:
    app: app-release
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: {{ .Values.jenkinsPort }}
      protocol: TCP